apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xelement-http
spec:
  compositeTypeRef:
    apiVersion: xp.semds.example.com/v1
    kind: Element
  mode: Pipeline
  pipeline:
    - step: patch-and-transform
      functionRef:
        name: function-patch-and-transform
      input:
        apiVersion: pt.fn.crossplane.io/v1beta1
        kind: Resources
        resources:
          - name: element-request
            base:
              apiVersion: http.m.crossplane.io/v1alpha2
              kind: Request
              spec:
                providerConfigRef:
                  kind: ProviderConfig
                  name: http-conf
                forProvider:
                  headers:
                    Content-Type:
                      - application/json
                  payload:
                    baseUrl: http://testapi.default.svc.cluster.local:3000/elements
                    body: '{"name":"PLACEHOLDER","description":"PLACEHOLDER"}'
                  mappings:
                    - action: CREATE
                      method: POST
                      url: .payload.baseUrl
                      body: '{ name: .payload.body.name, description: .payload.body.description }'
                    - action: OBSERVE
                      method: GET
                      url: .payload.baseUrl + "/" + (.response.body.id | tostring)
                    - action: UPDATE
                      method: PUT
                      url: .payload.baseUrl + "/" + (.response.body.id | tostring)
                      body: '{ name: .payload.body.name, description: .payload.body.description }'
                    - action: REMOVE
                      method: DELETE
                      url: .payload.baseUrl + "/" + (.response.body.id | tostring)
            patches:
              - type: CombineFromComposite
                combine:
                  variables:
                    - fromFieldPath: spec.name
                    - fromFieldPath: spec.description
                  strategy: string
                  string:
                    fmt: '{"name":"%s","description":"%s"}'
                toFieldPath: spec.forProvider.payload.body
              - type: ToCompositeFieldPath
                fromFieldPath: status.response.body
                toFieldPath: status.elementId
                transforms:
                  - type: string
                    string:
                      type: Regexp
                      regexp:
                        match: '"id":\s*([0-9]+)'
                        group: 1
                  - type: convert
                    convert:
                      toType: int
